# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:

  umdombot:
    build: ./
    container_name: umdombot
    hostname: umdombot
    domainname: dev.lan
    volumes:
      - ./:/usr/src/app
    networks:
      - my-net 
    command: python bot.py start --custom demo --log_level INFO 
    depends_on:
      - keydb 
      - mqttsubscr
    restart: unless-stopped  

  mqttsubscr:
    build: ./
    container_name: mqttsubscr
    hostname: mqttsubscr
    domainname: dev.lan
    volumes:
      - ./:/usr/src/app
    networks:
      - my-net 
    command: python mqttsubscr.py --custom demo --log_level INFO 
    depends_on:
      - keydb  
    restart: unless-stopped   

  keydb:
    image: eqalpha/keydb
    container_name: keydb
    networks:
      - my-net
    hostname: keydb
    domainname: dev.lan
    volumes:
      - ./volumes/keydb/data:/data
    # Включаем для записи на диск, место можно замонтировать в /volumes/keydb/data  
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes  
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    # ports:
    #   - "127.0.0.1:1883:1883"
    networks:
      - my-net
    hostname: mqtt
    domainname: dev.lan
    volumes:
      # - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    restart: unless-stopped  

  # mysql:
  #   image: mysql:8
  #   ports:
  #     - "127.0.0.1:3306:3306"
  #   networks:
  #     - my-net
  #   volumes:
  #     - ./volumes/mysql:/var/lib/mysql
  #     # Ниже 2 строки для подключения кастомного конфига
  #     # - ./images/mysql/start.sh:/etc/mysql/start.sh
  #     # - ./images/mysql/conf.d/zz-1-custom.cnf:/etc/mysql/conf.d/zz-1-custom.cnf
  #   hostname: web-mysql
  #   domainname: dev.lan
  #   # задаем пароль для root пользователя
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   command: mysqld --sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_ALL_TABLES
  #   restart: unless-stopped

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: unless-stopped
  #   ports:
  #     - 8080:80
  #   environment:
  #     # - PMA_ARBITRARY=1  
  #     - PMA_HOST=mysql
  #     - PMA_PORT=3306
  #   networks:
  #     - my-net  
  #   depends_on:
  #     - mysql 

networks:
    my-net:
        driver: bridge
